# your informations
author:
  name: Fernando Moraes
  email: m87.fernando@gmail.com

# site description
description: >- # this means to ignore newlines until "baseurl:"
  Thoughts and writings about software engineering by Fernando Moraes. 
  This work is licensed under a Creative Commons Attribution 4.0 International License. In other words, share generously but provide attribution.
    
# site url
baseurl: "/" # the subpath of your site, e.g. /blog
url: http://fmoraes87.github.io

# site title
title: fmoraes87

# site version
version: 1.0.0

# Social Media's
twitter_username: fmoraes87
github_username:  fmoraes87
linkedin_username: fmoraes87

defaultLang: en
languagesNames:
  en: /assets/icons/iconfinder_United-Kingdom-flag_32363.png
  pt_br: /assets/icons/iconfinder_Brazil-Flag_32181.png
#  zh: 中文

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: fmoraes87

# Build settings
markdown: kramdown
permalink: /:title
theme: minima
plugins:
  - jekyll-feed